### ISSUE TITLE
flake8 image is out of date; latest image is 6.0.0, flake8's latest version is 7.0.0

### ISSUE THREAD

**Issue by candrews** [alpine-docker/multi-arch-docker-images#5]
The latest image version is 6.0.0: https://hub.docker.com/r/alpine/flake8/tags

However, the latest version of flake8 is 7.0.0: https://pypi.org/project/flake8/

Can you please release version 7.0.0 of the `alpine/flake8` docker image?

Thank you!

**Comment by ozbillwang** [comment]
In fact, the image with the `latest` tag is version 7. Let me check why it didn't create version 7.0.0 as a tag.

**Comment by ozbillwang** [comment]
Fixed

**Comment by candrews** [comment]
Thank you!
